#!/bin/bash

source funcs

for num in 1 2 ; do
	ip netns del side$num &> /dev/null
	ip netns add side$num &> /dev/null
	ip netns exec side$num ip link set lo up
done

for num in 1 2 ; do
	ip link add e1$num type veth peer name e2$num 
	ip link set e1$num  netns side1 
	ip netns exec side1 ip link set e1$num up
	ip link set e2$num  netns side2 
	ip netns exec side2 ip link set e2$num up
done

$NS1 brctl addbr br
$NS1 brctl addif br e11
$NS1 brctl addif br e12
$NS1 ip link set dev br up
$NS1 ip addr add 192.168.9.1/24 dev br

$NS2 brctl addbr br
$NS2 brctl addif br e21
$NS2 brctl addif br e22
$NS2 ip link set dev br up
$NS2 ip addr add 192.168.9.2/24 dev br


$NS1 ping -c 1 192.168.9.3
