#! /bin/bash

BTRFS=/dev/sdb1

umount /btrfs
mkfs.btrfs -f -L demos $BTRFS 
[ -d /btrfs ] || mkdir /btrfs
mount -t btrfs $BTRFS /btrfs
btrfs subvolume create /btrfs/centos
docker export centos-base | tar -C /btrfs/centos -x -f -
cp eat/eat /btrfs/centos/usr/local/bin
btrfs subvolume snapshot /btrfs/centos /btrfs/demo1
btrfs subvolume snapshot /btrfs/centos /btrfs/demo2


if false ; then 
	BTRFS2=/dev/sda2
	btrfs dev add -f $BTRFS2 /btrfs
	btrfs file show /btrfs
	btrfs file info /btrfs
	btrfs file df /btrfs
	btrfs balance start -dconvert=raid1 -mconvert=raid1 /btrfs
	btrfs file show /btrfs
	btrfs file df /btrfs
fi

