#! /bin/bash

demo=${1:-demo1}

mount --make-rprivate /
mount -t btrfs -o subvol=$demo LABEL=demos /demos
mount -t proc none /demos/proc
mount -t sysfs none /demos/sys
cp /etc/resolv.conf /demos/etc/resolv.conf

[ -d /demos/old-root ] || mkdir /demos/old-root
pivot_root /demos /demos/old-root

hostname ${demo}
export PS1="[${demo}] "
chroot /


