#! /bin/bash

case "$1" in 
	*1)
ip tunnel add tunnel0 mode ipip remote 172.25.20.100 local 172.25.10.100
ip addr add 10.0.0.1 peer 10.0.0.2 dev tunnel0
ip link set tunl0 up
ip link set tunnel0 up
	;;

	*2)
ip tunnel add tunnel0 mode ipip remote 172.25.10.100 local 172.25.20.100
ip addr add 10.0.0.2 peer 10.0.0.1 dev tunnel0
ip link set tunl0 up
ip link set tunnel0 up
	;;
esac

